function cmake-llvm --wraps='cmake'
  cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DLLVM_LINK_LLVM_DYLIB=ON -DLLVM_OPTIMIZED_TABLEGEN=ON -DLLVM_APPEND_VC_REV=OFF -DLLVM_ENABLE_PROJECTS="clang;lld" -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../llvm
end
